### ISSUE TITLE
MACOS 0.8.11 - Won't build

### ISSUE THREAD

**Issue by ollydixon** [flutter-webrtc/flutter-webrtc#996]
Just upgraded to 0.8.11. Doing full refresh build.

Get the following error 

```
 error: no visible @interface for 'RTCDesktopMediaList' declares the selector 'UpdateSourceList'
        [_screen UpdateSourceList];
```

**Comment by cloudwebrtc** [comment]
I will create a hotfix

**Comment by simonbengtsson** [comment]
Tried now and had the same errors. Also tried creating a new project and adding the library which also causes the same errors.

```
flutter create macosbuildissue --platforms macos
flutter pub add flutter_webrtc
flutter build macos --debug # Causes build errors above
```

Does it work on macos for you? I'm using an intel Macbook Pro. I tried creating both a objective c and swift flutter project and both fails for me.

**Comment by cloudwebrtc** [comment]
OK， It might be a mistake on my part, I merged a branch in WIP to master (for testing) which caused this error, I'll do a hotfix to fix it.  sorry for that

**Comment by cloudwebrtc** [comment]
hey, did you clear the entire pod cache? If the cleanup still doesn't work, I think I need to bump up the pod spec about WebRTC.xframework by a version. sorry for that

```
duanweiwei@duanweiMBPIntel macosbuildissue % fvm flutter --version
Flutter 3.0.2 • channel unknown • unknown source
Framework • revision cd41fdd495 (5 weeks ago) • 2022-06-08 09:52:13 -0700
Engine • revision f15f824b57
Tools • Dart 2.17.3 • DevTools 2.12.2
duanweiwei@duanweiMBPIntel Test % fvm flutter create macosbuildissue --platforms macos
Creating project macosbuildissue...
Running "flutter pub get" in macosbuildissue...                     6.1s
Wrote 38 files.

All done!
In order to run your application, type:

  $ cd macosbuildissue
  $ flutter run

Your application code is in macosbuildissue/lib/main.dart.

duanweiwei@duanweiMBPIntel Test % cd macosbuildissue 
duanweiwei@duanweiMBPIntel macosbuildissue % fvm flutter pub add flutter_webrtc
Resolving dependencies...
  async 2.8.2 (2.9.0 available)
  characters 1.2.0 (1.2.1 available)
  clock 1.1.0 (1.1.1 available)
+ dart_webrtc 1.0.6
  fake_async 1.3.0 (1.3.1 available)
+ ffi 2.0.1
+ file 6.1.2
+ flutter_webrtc 0.8.11
  matcher 0.12.11 (0.12.12 available)
  material_color_utilities 0.1.4 (0.1.5 available)
  meta 1.7.0 (1.8.0 available)
  path 1.8.1 (1.8.2 available)
+ path_provider 2.0.11
+ path_provider_android 2.0.16
+ path_provider_ios 2.0.10
+ path_provider_linux 2.1.7
+ path_provider_macos 2.0.6
+ path_provider_platform_interface 2.0.4
+ path_provider_windows 2.1.0
+ platform 3.1.0
+ plugin_platform_interface 2.1.2
+ process 4.2.4
  source_span 1.8.2 (1.9.0 available)
  string_scanner 1.1.0 (1.1.1 available)
  term_glyph 1.2.0 (1.2.1 available)
  test_api 0.4.9 (0.4.12 available)
+ webrtc_interface 1.0.5
+ win32 2.7.0
+ xdg_directories 0.2.0+1
Downloading flutter_webrtc 0.8.11...
Changed 17 dependencies!
duanweiwei@duanweiMBPIntel macosbuildissue % fvm flutter build macos

💪 Building with sound null safety 💪

Running pod install...                                           2,374ms
4 warnings generated.
4 warnings generated.
Building macOS application...                                           

```

**Comment by cloudwebrtc** [comment]
@simonbengtsson I have updated the .xframework file in https://github.com/webrtc-sdk/Specs/releases/tag/97.4692.06, you can try to clear the pod cache and then mutate it, it should work fine

**Comment by ollydixon** [comment]
@cloudwebrtc thanks for your quick help.

But after running (M1 Max Macbook Pro)

```
rm -rf ~/Library/Caches/CocoaPods.
rm -rf ~/Library/Developer/Xcode/DerivedData/*
```

Go into "macos" and "ios" directories 
`pod deintegrate`

`Flutter clean`
`Delete Pods and Podfile.lock`

Re-run, doesn't work.

I cannot test with 0.8.12 as we still can't build it.
https://github.com/flutter-webrtc/flutter-webrtc/issues/1020

```
/Users/oliverdixon/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.12/macos/Classes/FlutterRTCDesktopCapturer.m:109:56: error: no visible @interface for 'RTCDesktopCapturer' declares the selector 'initWithDefaultScreen:'
        desktopCapturer  = [[RTCDesktopCapturer alloc] initWithDefaultScreen:videoSource];
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~
/Users/oliverdixon/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.12/macos/Classes/FlutterRTCDesktopCapturer.m:116:56: error: no visible @interface for 'RTCDesktopCapturer' declares the selector 'initWithSource:delegate:'
        desktopCapturer  = [[RTCDesktopCapturer alloc] initWithSource:source delegate:videoSource];
                            ~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/oliverdixon/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.12/macos/Classes/FlutterRTCDesktopCapturer.m:284:61: error: no visible @interface for 'RTCDesktopMediaList' declares the selector 'initWithType:'
        if(!_window) _window = [[RTCDesktopMediaList alloc] initWithType:RTCDesktopSourceTypeWindow];
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^~~~~~~~~~~~
/Users/oliverdixon/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.12/macos/Classes/FlutterRTCDesktopCapturer.m:285:18: error: no visible @interface for 'RTCDesktopMediaList' declares the selector 'UpdateSourceList'
        [_window UpdateSourceList];
         ~~~~~~~ ^~~~~~~~~~~~~~~~
```

**Comment by ollydixon** [comment]
Got it working

I needed to run in the following order (exactly)

```
rm -rf ~/Library/Developer/Xcode/DerivedData/*
rm -rf ~/Library/Caches/CocoaPods
rm -rf Pods
pod cache clean --all (macos + ios)
flutter clean (macos + ios)
flutter pub get (macos + ios)
```

Now time to reset all the build servers 🙈



FYI There's a few new warnings as well

```
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006001-0002612A0102801E }
{ platform:macOS, arch:x86_64, id:00006001-0002612A0102801E }
/Users/oliverdixon/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.12/macos/Classes/FlutterWebRTCPlugin.m:345:31: warning: incompatible pointer types sending 'NSString *' to parameter of type 'NSNumber * _Nonnull' [-Wincompatible-pointer-types]
                dataChannelId:dataChannelId
                              ^~~~~~~~~~~~~
In file included from /Users/oliverdixon/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.12/macos/Classes/FlutterWebRTCPlugin.m:4:
         dataChannelId:(nonnull NSNumber *)dataChannelId
                                           ^
/Users/oliverdixon/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.12/macos/Classes/FlutterWebRTCPlugin.m:366:82: warning: incompatible pointer types sending 'NSString *' to parameter of type 'RTCVideoSource * _Nonnull' [-Wincompatible-pointer-types]
                CapturerStopHandler stopHandler = self.videoCapturerStopHandlers[streamId];
                                                                                 ^~~~~~~~
In module 'Foundation' imported from /Users/oliverdixon/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.12/macos/Classes/FlutterWebRTCPlugin.h:7:
- (nullable ObjectType)objectForKeyedSubscript:(KeyType)key API_AVAILABLE(macos(10.8), ios(6.0), watchos(2.0), tvos(9.0));
                                                        ^
/Users/oliverdixon/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.8.12/macos/Classes/FlutterWebRTCPlugin.m:468:64: warning: incompatible pointer types initializing 'NSMutableDictionary<NSNumber *,RTCDataChannel *> *' with an expression of type 'NSMutableDictionary<NSString *,RTCDataChannel *> *' [-Wincompatible-pointer-types]
            NSMutableDictionary<NSNumber *, RTCDataChannel *> *dataChannels = peerConnection.dataChannels;
```
